services:

  db:
    image: postgres:16
    container_name: postgres_db_mmtorres
    environment:
      POSTGRES_DB: mmtorresoptical
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mmtorresoptical"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    image: lindtsey/mmtorresoptical-frontend:latest
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started

  backend:
    image: lindtsey/mmtorresoptical-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mmtorresoptical
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123

      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_SECRET_KEY: ${ENCRYPTION_SECRET_KEY}
      HASH_PEPPER: ${HASH_PEPPER}

volumes:
  postgres_data:
