package com.mmtorresoptical.OpticalClinicManagementSystem.services.report.generator.excel;

import com.mmtorresoptical.OpticalClinicManagementSystem.services.report.TabularReportDataset;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.WorkbookUtil;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class PoiXlsxTabularReportGenerator implements ExcelReportGenerator {

    private static final Logger logger = LoggerFactory.getLogger(PoiXlsxTabularReportGenerator.class);

    @Override
    public byte[] generate(TabularReportDataset dataset) {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            write(dataset, outputStream);
            return outputStream.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to generate Excel report", exception);
        }
    }

    @Override
    public void write(TabularReportDataset dataset, OutputStream outputStream) throws IOException {
        if (dataset == null) {
            throw new IllegalArgumentException("dataset must not be null");
        }

        List<String> columns = dataset.getColumns() == null ? List.of() : dataset.getColumns();
        List<List<Object>> rows = dataset.getRows() == null ? List.of() : dataset.getRows();

        logger.info("Generating Excel report: columns={}, rows={}", columns.size(), rows.size());

        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet(resolveSheetName(dataset));
            int rowNum = 0;

            Row titleRow = sheet.createRow(rowNum++);
            titleRow.createCell(0).setCellValue("Report Title:");
            titleRow.createCell(1).setCellValue(dataset.getMetadata().getTitle() != null
                    ? dataset.getMetadata().getTitle()
                    : "Report");

            Row byRow = sheet.createRow(rowNum++);
            byRow.createCell(0).setCellValue("Generated By:");
            byRow.createCell(1).setCellValue(dataset.getMetadata().getGeneratedBy() != null
                    ? dataset.getMetadata().getGeneratedBy()
                    : "System");

            Row atRow = sheet.createRow(rowNum++);
            atRow.createCell(0).setCellValue("Generated At:");
            String formattedDate = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                    .withZone(ZoneId.systemDefault())
                    .format(dataset.getMetadata().getGeneratedAt() != null
                            ? dataset.getMetadata().getGeneratedAt()
                            : java.time.Instant.now());
            atRow.createCell(1).setCellValue(formattedDate);

            rowNum++;

            Row headerRow = sheet.createRow(rowNum++);
            for (int columnIndex = 0; columnIndex < columns.size(); columnIndex++) {
                Cell cell = headerRow.createCell(columnIndex);
                cell.setCellValue(columns.get(columnIndex));
            }

            for (List<Object> rowData : rows) {
                Row row = sheet.createRow(rowNum++);
                if (rowData == null) {
                    continue;
                }

                for (int columnIndex = 0; columnIndex < rowData.size(); columnIndex++) {
                    Cell cell = row.createCell(columnIndex);
                    setCellValue(cell, rowData.get(columnIndex));
                }
            }

            for (int columnIndex = 0; columnIndex < columns.size(); columnIndex++) {
                sheet.autoSizeColumn(columnIndex);
            }

            workbook.write(outputStream);
        }
    }

    private String resolveSheetName(TabularReportDataset dataset) {
        String title = dataset.getMetadata() == null ? null : dataset.getMetadata().getTitle();
        if (title == null || title.isBlank()) {
            title = "report";
        }

        return WorkbookUtil.createSafeSheetName(title);
    }

    private void setCellValue(Cell cell, Object value) {
        if (value == null) {
            return;
        }

        if (value instanceof Number number) {
            cell.setCellValue(number.doubleValue());
            return;
        }

        if (value instanceof Boolean bool) {
            cell.setCellValue(bool);
            return;
        }

        if (value instanceof java.util.Date date) {
            cell.setCellValue(date);
            return;
        }

        cell.setCellValue(value.toString());
    }
}
