package com.mmtorresoptical.OpticalClinicManagementSystem.services.report.generator.pdf;

import com.mmtorresoptical.OpticalClinicManagementSystem.dto.product.ProductDetailsDTO;
import com.mmtorresoptical.OpticalClinicManagementSystem.services.report.ComprehensiveInventoryReportDataset;
import com.mmtorresoptical.OpticalClinicManagementSystem.objects.TopSellingProductDTO;
import com.mmtorresoptical.OpticalClinicManagementSystem.services.report.ReportMetadata;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.List;

@Service
public class PdfBoxInventoryAnalyticsReportGenerator {
    private static final PDType1Font HEADER_FONT = PDType1Font.HELVETICA_BOLD;
    private static final PDType1Font BODY_FONT = PDType1Font.HELVETICA;
    private static final float TITLE_FONT_SIZE = 16f;
    private static final float SECTION_FONT_SIZE = 12f;
    private static final float HEADER_FONT_SIZE = 11f;
    private static final float BODY_FONT_SIZE = 10f;
    private static final float MARGIN = 50f;
    private static final float LINE_HEIGHT = 14f;
    private static final float ROW_HEIGHT = 18f;
    private static final float CELL_PADDING = 2f;

    public byte[] generate(ComprehensiveInventoryReportDataset dataset) {
        if (dataset == null) {
            throw new IllegalArgumentException("dataset must not be null");
        }

        try (PDDocument document = new PDDocument();
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            renderDocument(document, dataset);
            document.save(outputStream);
            return outputStream.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to generate inventory analytics PDF", exception);
        }
    }

    private void renderDocument(PDDocument document, ComprehensiveInventoryReportDataset dataset) throws IOException {
        PageState state = startPage(document);
        state = writeMetadataHeader(document, state, dataset);
        state = writeSectionHeader(document, state, "Summary");
        state = writeSummaryLines(document, state, dataset);

        state = writeSectionHeader(document, state, "Low Stock Products");
        state = writeProductTable(document, state, dataset.getLowStockProducts(),
            "Low Stock Products", "Low Stock Threshold");

        state = writeSectionHeader(document, state, "Overstock Products");
        state = writeProductTable(document, state, dataset.getOverstockProducts(),
            "Overstock Products", "Overstock Threshold");

        state = writeSectionHeader(document, state, "Top-Selling Products");
        state = writeTopSellingProductsTable(document, state, dataset.getTopSellingProducts());

        state.contentStream.close();
    }

    private PageState startPage(PDDocument document) throws IOException {
        PDPage page = new PDPage(PDRectangle.LETTER);
        document.addPage(page);
        PDPageContentStream contentStream = new PDPageContentStream(document, page);
        float y = page.getMediaBox().getHeight() - MARGIN;
        return new PageState(page, contentStream, y);
    }

    private PageState ensureSpace(PDDocument document, PageState state, float requiredHeight) throws IOException {
        if (state.y - requiredHeight < MARGIN) {
            state.contentStream.close();
            return startPage(document);
        }
        return state;
    }

    private PageState writeMetadataHeader(PDDocument document,
                                          PageState state,
                                          ComprehensiveInventoryReportDataset dataset) throws IOException {
        String title = resolveTitle(dataset.getMetadata());
        String generatedBy = dataset.getMetadata().getGeneratedBy();
        String generatedAt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                .withZone(ZoneId.systemDefault())
                .format(dataset.getMetadata().getGeneratedAt());

        state = ensureSpace(document, state, TITLE_FONT_SIZE + (LINE_HEIGHT * 3) + 20f);

        writeText(state.contentStream, title, MARGIN, state.y, HEADER_FONT, TITLE_FONT_SIZE);
        state.y -= LINE_HEIGHT + 5f;
        writeText(state.contentStream, "Generated By: " + generatedBy, MARGIN, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;
        writeText(state.contentStream, "Generated At: " + generatedAt, MARGIN, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= 10f;

        state.contentStream.moveTo(MARGIN, state.y);
        state.contentStream.lineTo(state.page.getMediaBox().getWidth() - MARGIN, state.y);
        state.contentStream.stroke();

        state.y -= 20f;

        return state;
    }

    private PageState writeSectionHeader(PDDocument document, PageState state, String title) throws IOException {
        float pageTop = state.page.getMediaBox().getHeight() - MARGIN;
        float beforeSpacing = state.y < pageTop - 5f ? 15f : 0f;
        float afterSpacing = 4f;
        state = ensureSpace(document, state, SECTION_FONT_SIZE + LINE_HEIGHT + beforeSpacing + afterSpacing);
        state.y -= beforeSpacing;
        writeText(state.contentStream, title, MARGIN, state.y, HEADER_FONT, SECTION_FONT_SIZE);
        state.y -= LINE_HEIGHT;
        state.y -= afterSpacing;
        return state;
    }

    private PageState writeSummaryLines(PDDocument document,
                                        PageState state,
                                        ComprehensiveInventoryReportDataset dataset) throws IOException {
        String totalValue = formatCurrency(dataset.getTotalInventoryValue());
        String lowStock = String.valueOf(dataset.getTotalLowStockCount());
        String overstock = String.valueOf(dataset.getTotalOverstockCount());

        state = writeBodyLine(document, state, "Total Inventory Value: " + totalValue);
        state = writeBodyLine(document, state, "Low Stock Count: " + lowStock);
        state = writeBodyLine(document, state, "Overstock Count: " + overstock);
        state.y -= 10f;
        return state;
    }

    private PageState writeProductTable(PDDocument document,
                                        PageState state,
                                        List<ProductDetailsDTO> products,
                                        String sectionTitle,
                                        String thresholdHeader) throws IOException {
        List<ProductDetailsDTO> safeProducts = products == null ? Collections.emptyList() : products;
        if (safeProducts.isEmpty()) {
            return writeBodyLine(document, state, "No products available.");
        }

        List<String> headers = List.of("Product Name", "Category", "Quantity", thresholdHeader);
        float tableWidth = state.page.getMediaBox().getWidth() - (MARGIN * 2);
        float[] columnWidths = new float[] {
                tableWidth * 0.40f,
                tableWidth * 0.30f,
                tableWidth * 0.15f,
                tableWidth * 0.15f
        };

        state = ensureTableHeaderSpace(document, state, sectionTitle, headers, columnWidths);

        for (ProductDetailsDTO product : safeProducts) {
            if (state.y - ROW_HEIGHT < MARGIN) {
                state.contentStream.close();
                state = startPage(document);
                state = writeSectionHeader(document, state, sectionTitle);
                drawRow(state.contentStream, headers, MARGIN, state.y, columnWidths, true);
                state.y -= ROW_HEIGHT;
            }

            List<String> values = List.of(
                    resolveProductName(product),
                    resolveCategory(product),
                    resolveQuantity(product),
                    resolveThreshold(product, thresholdHeader)
            );
            drawRow(state.contentStream, values, MARGIN, state.y, columnWidths, false);
            state.y -= ROW_HEIGHT;
        }

        state.y -= 15f;
        return state;
    }

    private PageState writeTopSellingProductsTable(PDDocument document,
                                                   PageState state,
                                                   List<TopSellingProductDTO> products) throws IOException {
        List<TopSellingProductDTO> safeProducts = products == null ? Collections.emptyList() : products;
        if (safeProducts.isEmpty()) {
            return writeBodyLine(document, state, "No products available.");
        }

        List<String> headers = List.of("Product Name", "Category", "Total Quantity Sold", "Total Revenue");
        float tableWidth = state.page.getMediaBox().getWidth() - (MARGIN * 2);
        float[] columnWidths = new float[] {
                tableWidth * 0.40f,
                tableWidth * 0.25f,
                tableWidth * 0.175f,
                tableWidth * 0.175f
        };

        state = ensureTableHeaderSpace(document, state, "Top-Selling Products", headers, columnWidths);

        for (TopSellingProductDTO product : safeProducts) {
            if (state.y - ROW_HEIGHT < MARGIN) {
                state.contentStream.close();
                state = startPage(document);
                state = writeSectionHeader(document, state, "Top-Selling Products");
                drawRow(state.contentStream, headers, MARGIN, state.y, columnWidths, true);
                state.y -= ROW_HEIGHT;
            }

            List<String> values = List.of(
                    resolveTopSellingProductName(product),
                    resolveTopSellingCategory(product),
                    resolveTotalSold(product),
                    resolveTotalRevenue(product)
            );
            drawRow(state.contentStream, values, MARGIN, state.y, columnWidths, false);
            state.y -= ROW_HEIGHT;
        }

        state.y -= 15f;
        return state;
    }

    private PageState ensureTableHeaderSpace(PDDocument document,
                                             PageState state,
                                             String sectionTitle,
                                             List<String> headers,
                                             float[] columnWidths) throws IOException {
        float requiredHeight = (ROW_HEIGHT * 2) + 15f;
        if (state.y - requiredHeight < MARGIN) {
            state.contentStream.close();
            state = startPage(document);
            state = writeSectionHeader(document, state, sectionTitle);
        }
        drawRow(state.contentStream, headers, MARGIN, state.y, columnWidths, true);
        state.y -= ROW_HEIGHT;
        return state;
    }

    private void drawRow(PDPageContentStream contentStream,
                         List<String> values,
                         float startX,
                         float y,
                         float[] columnWidths,
                         boolean headerRow) throws IOException {
        PDType1Font font = headerRow ? HEADER_FONT : BODY_FONT;
        float fontSize = headerRow ? HEADER_FONT_SIZE : BODY_FONT_SIZE;

        float currentX = startX;
        for (int i = 0; i < values.size() && i < columnWidths.length; i++) {
            float columnWidth = columnWidths[i];
            contentStream.addRect(currentX, y - ROW_HEIGHT, columnWidth, ROW_HEIGHT);
            contentStream.stroke();

            String text = values.get(i) == null ? "" : values.get(i);
            String fittedText = fitToWidth(text, font, fontSize, columnWidth - (CELL_PADDING * 2));
            float textY = y - 13f;
            writeText(contentStream, fittedText, currentX + CELL_PADDING, textY, font, fontSize);
            currentX += columnWidth;
        }
    }

    private String fitToWidth(String text, PDType1Font font, float fontSize, float maxWidth) throws IOException {
        if (text == null || text.isEmpty()) {
            return "";
        }
        String candidate = text;
        float textWidth = font.getStringWidth(candidate) / 1000f * fontSize;
        if (textWidth <= maxWidth) {
            return candidate;
        }
        String ellipsis = "...";
        int end = candidate.length();
        while (end > 0) {
            String truncated = candidate.substring(0, end) + ellipsis;
            float width = font.getStringWidth(truncated) / 1000f * fontSize;
            if (width <= maxWidth) {
                return truncated;
            }
            end--;
        }
        return "";
    }

    private String resolveProductName(ProductDetailsDTO product) {
        if (product == null || product.getProductName() == null || product.getProductName().isBlank()) {
            return "Unknown";
        }
        return product.getProductName();
    }

    private String resolveCategory(ProductDetailsDTO product) {
        if (product == null || product.getCategory() == null || product.getCategory().isBlank()) {
            return "N/A";
        }
        return product.getCategory();
    }

    private String resolveQuantity(ProductDetailsDTO product) {
        if (product == null || product.getQuantity() == null) {
            return "N/A";
        }
        return product.getQuantity().toString();
    }

    private String resolveThreshold(ProductDetailsDTO product, String thresholdHeader) {
        if (product == null) {
            return "N/A";
        }
        Integer threshold = "Low Stock Threshold".equals(thresholdHeader)
                ? product.getLowLevelThreshold()
                : product.getOverstockedThreshold();
        return threshold == null ? "N/A" : threshold.toString();
    }

    private String resolveTopSellingProductName(TopSellingProductDTO product) {
        if (product == null || product.productName() == null || product.productName().isBlank()) {
            return "Unknown";
        }
        return product.productName();
    }

    private String resolveTopSellingCategory(TopSellingProductDTO product) {
        if (product == null || product.category() == null || product.category().isBlank()) {
            return "N/A";
        }
        return product.category();
    }

    private String resolveTotalSold(TopSellingProductDTO product) {
        if (product == null || product.totalSold() == null) {
            return "N/A";
        }
        return product.totalSold().toString();
    }

    private String resolveTotalRevenue(TopSellingProductDTO product) {
        if (product == null || product.totalRevenue() == null) {
            return "N/A";
        }
        return formatCurrency(product.totalRevenue());
    }

    private PageState writeBodyLine(PDDocument document, PageState state, String text) throws IOException {
        state = ensureSpace(document, state, LINE_HEIGHT);
        writeText(state.contentStream, text, MARGIN, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;
        return state;
    }

    private void writeText(PDPageContentStream contentStream,
                           String text,
                           float x,
                           float y,
                           PDType1Font font,
                           float fontSize) throws IOException {
        contentStream.beginText();
        contentStream.setFont(font, fontSize);
        contentStream.newLineAtOffset(x, y);
        contentStream.showText(text == null ? "" : text);
        contentStream.endText();
    }

    private String resolveTitle(ReportMetadata metadata) {
        if (metadata == null) {
            return "Inventory Analytics Report";
        }
        if (metadata.getTitle() != null && !metadata.getTitle().isBlank()) {
            return metadata.getTitle();
        }
        if (metadata.getReportType() != null) {
            return metadata.getReportType().name();
        }
        return "Inventory Analytics Report";
    }

    private String formatCurrency(BigDecimal value) {
        if (value == null) {
            return "N/A";
        }
        return value.toPlainString();
    }

    private static class PageState {
        private final PDPage page;
        private final PDPageContentStream contentStream;
        private float y;

        private PageState(PDPage page, PDPageContentStream contentStream, float y) {
            this.page = page;
            this.contentStream = contentStream;
            this.y = y;
        }
    }
}
