package com.mmtorresoptical.OpticalClinicManagementSystem.services.report.generator.pdf;

import com.mmtorresoptical.OpticalClinicManagementSystem.enums.PaymentType;
import com.mmtorresoptical.OpticalClinicManagementSystem.enums.TransactionStatus;
import com.mmtorresoptical.OpticalClinicManagementSystem.services.report.ReportMetadata;
import com.mmtorresoptical.OpticalClinicManagementSystem.services.report.transactionpdf.*;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@Service
public class PdfBoxTransactionReportGenerator {

    private static final PDType1Font HEADER_FONT = PDType1Font.HELVETICA_BOLD;
    private static final PDType1Font BODY_FONT = PDType1Font.HELVETICA;
    private static final PDType1Font ITALIC_FONT = PDType1Font.HELVETICA_OBLIQUE;
    private static final float TITLE_FONT_SIZE = 16f;
    private static final float SECTION_FONT_SIZE = 13f;
    private static final float SUBSECTION_FONT_SIZE = 11f;
    private static final float HEADER_FONT_SIZE = 10f;
    private static final float BODY_FONT_SIZE = 9f;
    private static final float SMALL_FONT_SIZE = 8f;
    private static final float MARGIN = 50f;
    private static final float LINE_HEIGHT = 14f;
    private static final float ROW_HEIGHT = 16f;
    private static final float CELL_PADDING = 2f;

    private static final DateTimeFormatter DATE_TIME_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd");

    public byte[] generate(TransactionHierarchicalReportDataset dataset) {
        if (dataset == null) {
            throw new IllegalArgumentException("dataset must not be null");
        }

        try (PDDocument document = new PDDocument();
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            renderDocument(document, dataset);
            document.save(outputStream);
            return outputStream.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to generate transaction PDF report", exception);
        }
    }

    // ─── Document rendering ───────────────────────────────────────────

    private void renderDocument(PDDocument document,
                                TransactionHierarchicalReportDataset dataset) throws IOException {
        PageState state = startPage(document);
        state = writeReportHeader(document, state, dataset);

        List<PaymentTypeSection> sections = dataset.getPaymentTypeSections();
        if (sections == null || sections.isEmpty()) {
            state = writeBodyLine(document, state, dataset.getEmptyMessage());
            state.contentStream.close();
            return;
        }

        // Overall summary
        state = writeOverallSummary(document, state, dataset.getSummary());

        // Each payment type section
        for (PaymentTypeSection section : sections) {
            state = writePaymentTypeSection(document, state, section);
        }

        state.contentStream.close();
    }

    // ─── Report header ────────────────────────────────────────────────

    private PageState writeReportHeader(PDDocument document,
                                        PageState state,
                                        TransactionHierarchicalReportDataset dataset) throws IOException {
        ReportMetadata metadata = dataset.getMetadata();
        String title = resolveTitle(metadata);
        String generatedBy = metadata != null ? metadata.getGeneratedBy() : "N/A";
        String generatedAt = metadata != null && metadata.getGeneratedAt() != null
                ? DATE_TIME_FMT.withZone(ZoneId.systemDefault()).format(metadata.getGeneratedAt())
                : "N/A";

        String dateRange = formatDateRange(dataset.getMinDate(), dataset.getMaxDate());

        float requiredHeight = TITLE_FONT_SIZE + (LINE_HEIGHT * 4) + 25f;
        state = ensureSpace(document, state, requiredHeight);

        writeText(state.contentStream, title, MARGIN, state.y, HEADER_FONT, TITLE_FONT_SIZE);
        state.y -= LINE_HEIGHT + 5f;
        writeText(state.contentStream, "Generated By: " + generatedBy,
                MARGIN, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;
        writeText(state.contentStream, "Generated At: " + generatedAt,
                MARGIN, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;
        if (dateRange != null) {
            writeText(state.contentStream, "Date Range: " + dateRange,
                    MARGIN, state.y, BODY_FONT, BODY_FONT_SIZE);
            state.y -= LINE_HEIGHT;
        }

        state.y -= 2f;
        drawHorizontalLine(state, MARGIN, state.page.getMediaBox().getWidth() - MARGIN);
        state.y -= 15f;

        return state;
    }

    // ─── Overall summary ──────────────────────────────────────────────

    private PageState writeOverallSummary(PDDocument document,
                                          PageState state,
                                          TransactionReportSummary summary) throws IOException {
        if (summary == null) {
            return state;
        }

        state = ensureSpace(document, state, SUBSECTION_FONT_SIZE + (LINE_HEIGHT * 4) + 20f);

        writeText(state.contentStream, "Overall Summary", MARGIN, state.y, HEADER_FONT, SUBSECTION_FONT_SIZE);
        state.y -= LINE_HEIGHT + 4f;

        writeText(state.contentStream,
                "Total Transactions: " + summary.getTotalCount()
                        + "    |    Total Amount: " + formatCurrency(summary.getTotalAmount()),
                MARGIN + 10f, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;

        writeText(state.contentStream,
                "Completed: " + summary.getCompletedCount()
                        + " (" + formatCurrency(summary.getCompletedAmount()) + ")"
                        + "    |    Voided: " + summary.getVoidedCount()
                        + " (" + formatCurrency(summary.getVoidedAmount()) + ")"
                        + "    |    Refunded: " + summary.getRefundedCount()
                        + " (" + formatCurrency(summary.getRefundedAmount()) + ")",
                MARGIN + 10f, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT + 20f;

        return state;
    }

    // ─── Payment type section ─────────────────────────────────────────

    private PageState writePaymentTypeSection(PDDocument document,
                                              PageState state,
                                              PaymentTypeSection section) throws IOException {

        // Section header with thick separator
        float sectionHeaderHeight = SECTION_FONT_SIZE + LINE_HEIGHT * 3 + 30f;
        state = ensureSpace(document, state, sectionHeaderHeight);

        // Double line separator before section
        drawThickHorizontalLine(state, MARGIN, state.page.getMediaBox().getWidth() - MARGIN);
        state.y -= 18f;

        String sectionTitle = section.getPaymentType().name() + " TRANSACTIONS";
        writeText(state.contentStream, sectionTitle, MARGIN, state.y, HEADER_FONT, SECTION_FONT_SIZE);
        state.y -= LINE_HEIGHT + 4f;

        // Section summary
        TransactionReportSummary summary = section.getSummary();
        if (summary != null) {
            writeText(state.contentStream,
                    "Count: " + summary.getTotalCount()
                            + "    |    Amount: " + formatCurrency(summary.getTotalAmount()),
                    MARGIN + 10f, state.y, BODY_FONT, BODY_FONT_SIZE);
            state.y -= LINE_HEIGHT + 14f;
        }

        // Status groups
        if (section.getCompleted() != null) {
            state = writeStatusGroup(document, state, "COMPLETED", section.getCompleted(), section.getPaymentType());
        }
        if (section.getVoided() != null) {
            state = writeStatusGroup(document, state, "VOIDED", section.getVoided(), section.getPaymentType());
        }
        if (section.getRefunded() != null) {
            state = writeStatusGroup(document, state, "REFUNDED", section.getRefunded(), section.getPaymentType());
        }

        state.y -= 10f;
        return state;
    }

    // ─── Status group ─────────────────────────────────────────────────

    private PageState writeStatusGroup(PDDocument document,
                                       PageState state,
                                       String statusLabel,
                                       StatusSection statusSection,
                                       PaymentType paymentType) throws IOException {
        List<TransactionEntry> transactions = statusSection.getTransactions();
        if (transactions == null || transactions.isEmpty()) {
            return state;
        }

        // Status sub-header
        state = ensureSpace(document, state, SUBSECTION_FONT_SIZE + LINE_HEIGHT + 20f);
        drawHorizontalLine(state, MARGIN, state.page.getMediaBox().getWidth() - MARGIN);
        state.y -= 14f;
        writeText(state.contentStream, statusLabel, MARGIN + 5f, state.y, HEADER_FONT, SUBSECTION_FONT_SIZE);
        state.y -= LINE_HEIGHT + 10f;

        for (int i = 0; i < transactions.size(); i++) {
            state = writeTransactionBlock(document, state, transactions.get(i), paymentType);

            // Dashed separator between transactions (not after the last one)
            if (i < transactions.size() - 1) {
                state = ensureSpace(document, state, LINE_HEIGHT);
                drawDashedLine(state, MARGIN + 20f, state.page.getMediaBox().getWidth() - MARGIN - 20f);
                state.y -= 10f;
            }
        }

        state.y -= 8f;
        return state;
    }

    // ─── Individual transaction block ─────────────────────────────────

    private PageState writeTransactionBlock(PDDocument document,
                                            PageState state,
                                            TransactionEntry entry,
                                            PaymentType paymentType) throws IOException {
        float indent = MARGIN + 15f;

        // Estimate minimum space for the transaction header
        state = ensureSpace(document, state, LINE_HEIGHT * 6 + 20f);

        // Transaction ID
        writeText(state.contentStream, "Transaction: " + formatUuid(entry.getId()),
                indent, state.y, HEADER_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;

        // Date
        writeText(state.contentStream, "Date: " + formatDateTime(entry.getDate()),
                indent, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;

        // Status
        writeText(state.contentStream, "Status: " + entry.getStatus().name(),
                indent, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;

        // Total amount
        writeText(state.contentStream, "Total Amount: " + formatCurrency(entry.getTotalAmount()),
                indent, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;

        // Customer
        if (entry.getCustomerName() != null && !entry.getCustomerName().isBlank()) {
            writeText(state.contentStream, "Customer: " + entry.getCustomerName(),
                    indent, state.y, BODY_FONT, BODY_FONT_SIZE);
            state.y -= LINE_HEIGHT;
        }

        // Cashier
        if (entry.getCashierName() != null && !entry.getCashierName().isBlank()) {
            writeText(state.contentStream, "Processed By: " + entry.getCashierName(),
                    indent, state.y, BODY_FONT, BODY_FONT_SIZE);
            state.y -= LINE_HEIGHT;
        }

        // Payment-type-specific details
        state = writePaymentSpecificDetails(document, state, entry, paymentType, indent);

        // Status-specific details
        state = writeStatusSpecificDetails(document, state, entry, indent);

        // Items table
        state = writeItemsSection(document, state, entry, indent);

        state.y -= 6f;
        return state;
    }

    // ─── Payment-specific details ─────────────────────────────────────

    private PageState writePaymentSpecificDetails(PDDocument document,
                                                  PageState state,
                                                  TransactionEntry entry,
                                                  PaymentType paymentType,
                                                  float indent) throws IOException {
        if (paymentType == PaymentType.CASH) {
            if (entry.getCashTender() != null) {
                state = ensureSpace(document, state, LINE_HEIGHT * 2);
                writeText(state.contentStream, "Cash Tender: " + formatCurrency(entry.getCashTender()),
                        indent, state.y, BODY_FONT, BODY_FONT_SIZE);
                state.y -= LINE_HEIGHT;
            }
            if (entry.getChange() != null) {
                writeText(state.contentStream, "Change: " + formatCurrency(entry.getChange()),
                        indent, state.y, BODY_FONT, BODY_FONT_SIZE);
                state.y -= LINE_HEIGHT;
            }
        } else if (paymentType == PaymentType.GCASH) {
            state = ensureSpace(document, state, LINE_HEIGHT * 2);
            if (entry.getReferenceNumber() != null && !entry.getReferenceNumber().isBlank()) {
                writeText(state.contentStream, "GCash Reference: " + entry.getReferenceNumber(),
                        indent, state.y, BODY_FONT, BODY_FONT_SIZE);
                state.y -= LINE_HEIGHT;
            }
            if (entry.getGcashPaymentImgDir() != null && !entry.getGcashPaymentImgDir().isBlank()) {
                writeText(state.contentStream, "Payment Image: " + entry.getGcashPaymentImgDir(),
                        indent, state.y, ITALIC_FONT, SMALL_FONT_SIZE);
                state.y -= LINE_HEIGHT;
            }
        }

        return state;
    }

    // ─── Status-specific details ──────────────────────────────────────

    private PageState writeStatusSpecificDetails(PDDocument document,
                                                 PageState state,
                                                 TransactionEntry entry,
                                                 float indent) throws IOException {
        if (entry.getStatus() == TransactionStatus.VOIDED) {
            state = ensureSpace(document, state, LINE_HEIGHT * 3);
            state.y -= 3f;
            writeText(state.contentStream, "*** VOIDED ***",
                    indent, state.y, HEADER_FONT, BODY_FONT_SIZE);
            state.y -= LINE_HEIGHT;

            if (entry.getVoidReason() != null && !entry.getVoidReason().isBlank()) {
                writeText(state.contentStream, "Reason: " + entry.getVoidReason(),
                        indent, state.y, BODY_FONT, BODY_FONT_SIZE);
                state.y -= LINE_HEIGHT;
            }
            if (entry.getVoidedBy() != null && !entry.getVoidedBy().isBlank()) {
                writeText(state.contentStream, "Voided By: " + entry.getVoidedBy(),
                        indent, state.y, BODY_FONT, BODY_FONT_SIZE);
                state.y -= LINE_HEIGHT;
            }
            if (entry.getVoidedAt() != null) {
                writeText(state.contentStream, "Voided At: " + formatDateTime(entry.getVoidedAt()),
                        indent, state.y, BODY_FONT, BODY_FONT_SIZE);
                state.y -= LINE_HEIGHT;
            }
        }

        return state;
    }

    // ─── Items section ────────────────────────────────────────────────

    private PageState writeItemsSection(PDDocument document,
                                        PageState state,
                                        TransactionEntry entry,
                                        float indent) throws IOException {
        List<TransactionItemEntry> items = entry.getItems();
        if (items == null || items.isEmpty()) {
            return state;
        }

        state.y -= 8f;

        if (entry.getStatus() == TransactionStatus.PARTIALLY_REFUNDED) {
            // Split into refunded and non-refunded
            List<TransactionItemEntry> refundedItems = new ArrayList<>();
            List<TransactionItemEntry> nonRefundedItems = new ArrayList<>();

            for (TransactionItemEntry item : items) {
                if (item.getRefundedQuantity() != null && item.getRefundedQuantity() > 0) {
                    refundedItems.add(item);
                } else {
                    nonRefundedItems.add(item);
                }
            }

            if (!nonRefundedItems.isEmpty()) {
                state = ensureSpace(document, state, LINE_HEIGHT + ROW_HEIGHT * 2 + 10f);
                writeText(state.contentStream, "Non-Refunded Items:",
                        indent, state.y, HEADER_FONT, SMALL_FONT_SIZE);
                state.y -= 10f;
                state = writeItemsTable(document, state, nonRefundedItems, indent, false);
            }

            if (!refundedItems.isEmpty()) {
                state.y -= 10f;
                state = ensureSpace(document, state, LINE_HEIGHT + ROW_HEIGHT * 2 + 10f);
                writeText(state.contentStream, "Refunded Items:",
                        indent, state.y, HEADER_FONT, SMALL_FONT_SIZE);
                state.y -= 10f;
                state = writeItemsTable(document, state, refundedItems, indent, true);
            }

        } else if (entry.getStatus() == TransactionStatus.FULLY_REFUNDED) {
            state = ensureSpace(document, state, LINE_HEIGHT + ROW_HEIGHT * 2 + 10f);
            writeText(state.contentStream, "Refunded Items (All items refunded):",
                    indent, state.y, HEADER_FONT, SMALL_FONT_SIZE);
            state.y -= 10f;
            state = writeItemsTable(document, state, items, indent, true);

        } else {
            // COMPLETED or VOIDED — regular items table
            state = ensureSpace(document, state, LINE_HEIGHT + ROW_HEIGHT * 2 + 10f);
            writeText(state.contentStream, "Items:",
                    indent, state.y, HEADER_FONT, SMALL_FONT_SIZE);
            state.y -= 10f;
            state = writeItemsTable(document, state, items, indent, false);
        }

        return state;
    }

    // ─── Items table ──────────────────────────────────────────────────

    private PageState writeItemsTable(PDDocument document,
                                      PageState state,
                                      List<TransactionItemEntry> items,
                                      float indent,
                                      boolean showRefundColumns) throws IOException {
        float tableWidth = state.page.getMediaBox().getWidth() - indent - MARGIN;

        List<String> headers;
        float[] columnWidths;

        if (showRefundColumns) {
            headers = List.of("Product", "Qty", "Price", "Discount", "Subtotal", "Ref Qty", "Ref Amt");
            columnWidths = new float[]{
                    tableWidth * 0.25f,
                    tableWidth * 0.08f,
                    tableWidth * 0.13f,
                    tableWidth * 0.14f,
                    tableWidth * 0.14f,
                    tableWidth * 0.10f,
                    tableWidth * 0.16f
            };
        } else {
            headers = List.of("Product", "Qty", "Unit Price", "Discount", "Subtotal");
            columnWidths = new float[]{
                    tableWidth * 0.32f,
                    tableWidth * 0.10f,
                    tableWidth * 0.18f,
                    tableWidth * 0.18f,
                    tableWidth * 0.22f
            };
        }

        // Header row
        state = ensureSpace(document, state, ROW_HEIGHT * 2);
        drawItemRow(state.contentStream, headers, indent, state.y, columnWidths, true);
        state.y -= ROW_HEIGHT;

        // Data rows
        for (TransactionItemEntry item : items) {
            if (state.y - ROW_HEIGHT < MARGIN) {
                state.contentStream.close();
                state = startPage(document);
                drawItemRow(state.contentStream, headers, indent, state.y, columnWidths, true);
                state.y -= ROW_HEIGHT;
            }

            List<String> values;
            if (showRefundColumns) {
                values = List.of(
                        safe(item.getProductName()),
                        safeInt(item.getQuantity()),
                        formatCurrency(item.getUnitPrice()),
                        formatDiscount(item),
                        formatCurrency(item.getSubtotal()),
                        safeInt(item.getRefundedQuantity()),
                        formatCurrency(item.getRefundAmount())
                );
            } else {
                values = List.of(
                        safe(item.getProductName()),
                        safeInt(item.getQuantity()),
                        formatCurrency(item.getUnitPrice()),
                        formatDiscount(item),
                        formatCurrency(item.getSubtotal())
                );
            }

            drawItemRow(state.contentStream, values, indent, state.y, columnWidths, false);
            state.y -= ROW_HEIGHT;
        }

        state.y -= 8f;
        return state;
    }

    private void drawItemRow(PDPageContentStream contentStream,
                             List<String> values,
                             float startX,
                             float y,
                             float[] columnWidths,
                             boolean headerRow) throws IOException {
        PDType1Font font = headerRow ? HEADER_FONT : BODY_FONT;
        float fontSize = headerRow ? SMALL_FONT_SIZE : SMALL_FONT_SIZE;

        float currentX = startX;
        for (int i = 0; i < values.size() && i < columnWidths.length; i++) {
            float colWidth = columnWidths[i];
            contentStream.addRect(currentX, y - ROW_HEIGHT, colWidth, ROW_HEIGHT);
            contentStream.stroke();

            String text = values.get(i) == null ? "" : values.get(i);
            String fittedText = fitToWidth(text, font, fontSize, colWidth - (CELL_PADDING * 2));
            float textY = y - 12f;
            writeText(contentStream, fittedText, currentX + CELL_PADDING, textY, font, fontSize);
            currentX += colWidth;
        }
    }

    // ─── Drawing helpers ──────────────────────────────────────────────

    private void drawHorizontalLine(PageState state, float startX, float endX) throws IOException {
        state.contentStream.moveTo(startX, state.y);
        state.contentStream.lineTo(endX, state.y);
        state.contentStream.stroke();
    }

    private void drawThickHorizontalLine(PageState state, float startX, float endX) throws IOException {
        state.contentStream.setLineWidth(1.5f);
        state.contentStream.moveTo(startX, state.y);
        state.contentStream.lineTo(endX, state.y);
        state.contentStream.stroke();
        state.contentStream.setLineWidth(1f);
    }

    private void drawDashedLine(PageState state, float startX, float endX) throws IOException {
        state.contentStream.setLineDashPattern(new float[]{3, 3}, 0);
        state.contentStream.moveTo(startX, state.y);
        state.contentStream.lineTo(endX, state.y);
        state.contentStream.stroke();
        state.contentStream.setLineDashPattern(new float[]{}, 0);
    }

    // ─── Page management ──────────────────────────────────────────────

    private PageState startPage(PDDocument document) throws IOException {
        PDPage page = new PDPage(PDRectangle.LETTER);
        document.addPage(page);
        PDPageContentStream contentStream = new PDPageContentStream(document, page);
        float y = page.getMediaBox().getHeight() - MARGIN;
        return new PageState(page, contentStream, y);
    }

    private PageState ensureSpace(PDDocument document,
                                  PageState state,
                                  float requiredHeight) throws IOException {
        if (state.y - requiredHeight < MARGIN) {
            state.contentStream.close();
            return startPage(document);
        }
        return state;
    }

    private PageState writeBodyLine(PDDocument document,
                                    PageState state,
                                    String text) throws IOException {
        state = ensureSpace(document, state, LINE_HEIGHT);
        writeText(state.contentStream, text, MARGIN, state.y, BODY_FONT, BODY_FONT_SIZE);
        state.y -= LINE_HEIGHT;
        return state;
    }

    // ─── Text rendering ───────────────────────────────────────────────

    private void writeText(PDPageContentStream contentStream,
                           String text,
                           float x,
                           float y,
                           PDType1Font font,
                           float fontSize) throws IOException {
        contentStream.beginText();
        contentStream.setFont(font, fontSize);
        contentStream.newLineAtOffset(x, y);
        contentStream.showText(text == null ? "" : text);
        contentStream.endText();
    }

    private String fitToWidth(String text,
                              PDType1Font font,
                              float fontSize,
                              float maxWidth) throws IOException {
        if (text == null || text.isEmpty()) {
            return "";
        }
        float textWidth = font.getStringWidth(text) / 1000f * fontSize;
        if (textWidth <= maxWidth) {
            return text;
        }
        String ellipsis = "...";
        int end = text.length();
        while (end > 0) {
            String truncated = text.substring(0, end) + ellipsis;
            float width = font.getStringWidth(truncated) / 1000f * fontSize;
            if (width <= maxWidth) {
                return truncated;
            }
            end--;
        }
        return "";
    }

    // ─── Formatting helpers ───────────────────────────────────────────

    private String resolveTitle(ReportMetadata metadata) {
        if (metadata == null) {
            return "Transaction Report";
        }
        if (metadata.getTitle() != null && !metadata.getTitle().isBlank()) {
            return metadata.getTitle();
        }
        if (metadata.getReportType() != null) {
            return metadata.getReportType().name();
        }
        return "Transaction Report";
    }

    private String formatCurrency(BigDecimal value) {
        if (value == null) {
            return "-";
        }
        return value.toPlainString();
    }

    private String formatDateTime(LocalDateTime dateTime) {
        if (dateTime == null) {
            return "N/A";
        }
        return dateTime.format(DATE_TIME_FMT);
    }

    private String formatDateRange(LocalDate minDate, LocalDate maxDate) {
        if (minDate == null && maxDate == null) {
            return null;
        }
        String from = minDate != null ? minDate.format(DATE_FMT) : "Beginning";
        String to = maxDate != null ? maxDate.format(DATE_FMT) : "Present";
        return from + " to " + to;
    }

    private String formatDiscount(TransactionItemEntry item) {
        if (item.getDiscountType() == null || item.getDiscountValue() == null) {
            return "-";
        }
        return switch (item.getDiscountType()) {
            case PERCENT -> item.getDiscountValue().toPlainString() + "%";
            case FIXED -> formatCurrency(item.getDiscountValue());
        };
    }

    private String formatUuid(java.util.UUID uuid) {
        if (uuid == null) {
            return "N/A";
        }
        return uuid.toString();
    }

    private String safe(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }

    private String safeInt(Integer value) {
        return value == null ? "-" : value.toString();
    }

    // ─── Inner class ──────────────────────────────────────────────────

    private static class PageState {
        private final PDPage page;
        private final PDPageContentStream contentStream;
        private float y;

        private PageState(PDPage page, PDPageContentStream contentStream, float y) {
            this.page = page;
            this.contentStream = contentStream;
            this.y = y;
        }
    }
}
